<?php

namespace Database\Seeders;

use App\Models\Muscle;
use App\Models\Exercise;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class ExercisesSeeder extends Seeder
{
    public function run()
    {
        $exercises = [
            // Triceps
            [
                'name' => 'Triceps Pushdown',
                'muscle_id' => Muscle::where('name', 'triceps')->first()->id,
                'slug' => 'triceps-pushdown',
                'img' => 'triceps-pushdown.jpg',
                'tutorial' => 'triceps-pushdown-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::TRICEPS_GLOBAL,
            ],
            [
                'name' => 'Skull Crushers',
                'muscle_id' => Muscle::where('name', 'triceps')->first()->id,
                'slug' => 'skull-crushers',
                'img' => 'skull-crushers.jpg',
                'tutorial' => 'skull-crushers-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::TRICEPS_LONG,
            ],
            [
                'name' => 'Triceps Dips',
                'muscle_id' => Muscle::where('name', 'triceps')->first()->id,
                'slug' => 'triceps-dips',
                'img' => 'triceps-dips.jpg',
                'tutorial' => 'triceps-dips-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::TRICEPS_LATERAL,
            ],
            [
                'name' => 'Close Grip Bench Press',
                'muscle_id' => Muscle::where('name', 'triceps')->first()->id,
                'slug' => 'close-grip-bench-press',
                'img' => 'close-grip-bench-press.jpg',
                'tutorial' => 'close-grip-bench-press-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::TRICEPS_GLOBAL,
            ],
            [
                'name' => 'Triceps Kickbacks',
                'muscle_id' => Muscle::where('name', 'triceps')->first()->id,
                'slug' => 'triceps-kickbacks',
                'img' => 'triceps-kickbacks.jpg',
                'tutorial' => 'triceps-kickbacks-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::TRICEPS_LATERAL,
            ],
            [
                'name' => 'Diamond Push-Ups',
                'muscle_id' => Muscle::where('name', 'triceps')->first()->id,
                'slug' => 'diamond-push-ups',
                'img' => 'diamond-push-ups.jpg',
                'tutorial' => 'diamond-push-ups-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::TRICEPS_LONG,
            ],
            // Shoulders
            [
                'name' => 'Military Press',
                'muscle_id' => Muscle::where('name', 'shoulders')->first()->id,
                'slug' => 'military-press',
                'img' => 'military-press.jpg',
                'tutorial' => 'military-press-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::SHOULDER_ANTERIOR,
            ],
            [
                'name' => 'Lateral Raises',
                'muscle_id' => Muscle::where('name', 'shoulders')->first()->id,
                'slug' => 'lateral-raises',
                'img' => 'lateral-raises.jpg',
                'tutorial' => 'lateral-raises-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::SHOULDER_MEDIAN,
            ],
            [
                'name' => 'Rear Delt Flyes',
                'muscle_id' => Muscle::where('name', 'shoulders')->first()->id,
                'slug' => 'rear-delt-flyes',
                'img' => 'rear-delt-flyes.jpg',
                'tutorial' => 'rear-delt-flyes-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::SHOULDER_POSTERIOR,
            ],
            [
                'name' => 'Front Raises',
                'muscle_id' => Muscle::where('name', 'shoulders')->first()->id,
                'slug' => 'front-raises',
                'img' => 'front-raises.jpg',
                'tutorial' => 'front-raises-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::SHOULDER_ANTERIOR,
            ],
            [
                'name' => 'Seated Dumbbell Press',
                'muscle_id' => Muscle::where('name', 'shoulders')->first()->id,
                'slug' => 'seated-dumbbell-press',
                'img' => 'seated-dumbbell-press.jpg',
                'tutorial' => 'seated-dumbbell-press-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::SHOULDER_MEDIAN,
            ],
            [
                'name' => 'Face Pulls',
                'muscle_id' => Muscle::where('name', 'shoulders')->first()->id,
                'slug' => 'face-pulls',
                'img' => 'face-pulls.jpg',
                'tutorial' => 'face-pulls-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::SHOULDER_POSTERIOR,
            ],
            // Pectorals
            [
                'name' => 'Bench Press',
                'muscle_id' => Muscle::where('name', 'pectorals')->first()->id,
                'slug' => 'bench-press',
                'img' => 'bench-press.jpg',
                'tutorial' => 'bench-press-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::PEC_GRAND_PECTORAL,
            ],
            [
                'name' => 'Incline Dumbbell Press',
                'muscle_id' => Muscle::where('name', 'pectorals')->first()->id,
                'slug' => 'incline-dumbbell-press',
                'img' => 'incline-dumbbell-press.jpg',
                'tutorial' => 'incline-dumbbell-press-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::PEC_SUPERIOR,
            ],
            [
                'name' => 'Chest Flyes',
                'muscle_id' => Muscle::where('name', 'pectorals')->first()->id,
                'slug' => 'chest-flyes',
                'img' => 'chest-flyes.jpg',
                'tutorial' => 'chest-flyes-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::PEC_MEDIAN,
            ],
            [
                'name' => 'Push-Ups',
                'muscle_id' => Muscle::where('name', 'pectorals')->first()->id,
                'slug' => 'push-ups',
                'img' => 'push-ups.jpg',
                'tutorial' => 'push-ups-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::PEC_GRAND_PECTORAL,
            ],
            [
                'name' => 'Incline Bench Press',
                'muscle_id' => Muscle::where('name', 'pectorals')->first()->id,
                'slug' => 'incline-bench-press',
                'img' => 'incline-bench-press.jpg',
                'tutorial' => 'incline-bench-press-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::PEC_SUPERIOR,
            ],
            [
                'name' => 'Decline Bench Press',
                'muscle_id' => Muscle::where('name', 'pectorals')->first()->id,
                'slug' => 'decline-bench-press',
                'img' => 'decline-bench-press.jpg',
                'tutorial' => 'decline-bench-press-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::PEC_INFERIOR,
            ],
            // Bras
            [
                'name' => 'Bicep Curls',
                'muscle_id' => Muscle::where('name', 'arms')->first()->id,
                'slug' => 'bicep-curls',
                'img' => 'bicep-curls.jpg',
                'tutorial' => 'bicep-curls-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => true,
                'muscle_part' => Exercise::BRAS_BICEPS,
            ],
            [
                'name' => 'Hammer Curls',
                'muscle_id' => Muscle::where('name', 'arms')->first()->id,
                'slug' => 'hammer-curls',
                'img' => 'hammer-curls.jpg',
                'tutorial' => 'hammer-curls-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => true,
                'muscle_part' => Exercise::BRAS_BICEPS,
            ],
            [
                'name' => 'Concentration Curls',
                'muscle_id' => Muscle::where('name', 'arms')->first()->id,
                'slug' => 'concentration-curls',
                'img' => 'concentration-curls.jpg',
                'tutorial' => 'concentration-curls-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'isolation',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::BRAS_BICEPS,
            ],
            [
                'name' => 'Reverse Curls',
                'muscle_id' => Muscle::where('name', 'arms')->first()->id,
                'slug' => 'reverse-curls',
                'img' => 'reverse-curls.jpg',
                'tutorial' => 'reverse-curls-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'isolation',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::BRAS_BICEPS,
            ],
            [
                'name' => 'Wrist Curls',
                'muscle_id' => Muscle::where('name', 'arms')->first()->id,
                'slug' => 'wrist-curls',
                'img' => 'wrist-curls.jpg',
                'tutorial' => 'wrist-curls-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'isolation',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::BRAS_AVANT_BRAS,
            ],
            // Dos
            [
                'name' => 'Tirage horizontal',
                'muscle_id' => Muscle::where('name', 'back')->first()->id,
                'slug' => 'tirage-horizontal',
                'img' => 'tirage-horizontal.jpg',
                'tutorial' => 'tirage-horizontal-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => true,
                'muscle_part' => Exercise::DOS_GRAND_DORSAL,
            ],
            [
                'name' => 'Élévations de trapèzes',
                'muscle_id' => Muscle::where('name', 'back')->first()->id,
                'slug' => 'elevations-trapezes',
                'img' => 'elevations-trapezes.jpg',
                'tutorial' => 'elevations-trapezes-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'isolation',
                'difficulty' => 'medium',
                'polyarticular' => false,
                'muscle_part' => Exercise::DOS_TRAPEZES,
            ],
            [
                'name' => 'Rowing à la barre en T',
                'muscle_id' => Muscle::where('name', 'back')->first()->id,
                'slug' => 'rowing-barre-t',
                'img' => 'rowing-barre-t.jpg',
                'tutorial' => 'rowing-barre-t-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'medium',
                'polyarticular' => true,
                'muscle_part' => Exercise::DOS_RHOMBOIDES,
            ],
            [
                'name' => 'Pull-ups',
                'muscle_id' => Muscle::where('name', 'back')->first()->id,
                'slug' => 'pull-ups',
                'img' => 'pull-ups.jpg',
                'tutorial' => 'pull-ups-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'hard',
                'polyarticular' => true,
                'muscle_part' => Exercise::DOS_GRAND_ROND,
            ],
            [
                'name' => 'Extensions lombaires',
                'muscle_id' => Muscle::where('name', 'back')->first()->id,
                'slug' => 'extensions-lombaires',
                'img' => 'extensions-lombaires.jpg',
                'tutorial' => 'extensions-lombaires-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'isolation',
                'difficulty' => 'easy',
                'polyarticular' => false,
                'muscle_part' => Exercise::DOS_LOMBAIRES,
            ],
            // Quadriceps
            [
                'name' => 'Squats',
                'muscle_id' => Muscle::where('name', 'legs')->first()->id,
                'slug' => 'squats',
                'img' => 'squats.jpg',
                'tutorial' => 'squats-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'intermediate',
                'polyarticular' => true,
                'muscle_part' => Exercise::LEGS_QUADRICEPS,
            ],
            [
                'name' => 'Leg Press',
                'muscle_id' => Muscle::where('name', 'legs')->first()->id,
                'slug' => 'leg-press',
                'img' => 'leg-press.jpg',
                'tutorial' => 'leg-press-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'intermediate',
                'polyarticular' => true,
                'muscle_part' => Exercise::LEGS_QUADRICEPS,
            ],
            // Ischio-jambiers
            [
                'name' => 'Soulevé de terre',
                'muscle_id' => Muscle::where('name', 'legs')->first()->id,
                'slug' => 'souleve-de-terre',
                'img' => 'souleve-de-terre.jpg',
                'tutorial' => 'souleve-de-terre-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'advanced',
                'polyarticular' => true,
                'muscle_part' => Exercise::LEGS_HAMSTRINGS,
            ],
            [
                'name' => 'Curl des ischio-jambiers',
                'muscle_id' => Muscle::where('name', 'legs')->first()->id,
                'slug' => 'curl-des-ischio-jambiers',
                'img' => 'curl-des-ischio-jambiers.jpg',
                'tutorial' => 'curl-des-ischio-jambiers-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'isolated',
                'difficulty' => 'intermediate',
                'polyarticular' => false,
                'muscle_part' => Exercise::LEGS_HAMSTRINGS,
            ],
            // Mollets
            [
                'name' => 'Élévations de mollets debout',
                'muscle_id' => Muscle::where('name', 'legs')->first()->id,
                'slug' => 'elevations-de-mollets-debout',
                'img' => 'elevations-de-mollets-debout.jpg',
                'tutorial' => 'elevations-de-mollets-debout-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'isolated',
                'difficulty' => 'beginner',
                'polyarticular' => false,
                'muscle_part' => Exercise::LEGS_CALVES,
            ],
            [
                'name' => 'Élévations de mollets assis',
                'muscle_id' => Muscle::where('name', 'legs')->first()->id,
                'slug' => 'elevations-de-mollets-assis',
                'img' => 'elevations-de-mollets-assis.jpg',
                'tutorial' => 'elevations-de-mollets-assis-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'isolated',
                'difficulty' => 'beginner',
                'polyarticular' => false,
                'muscle_part' => Exercise::LEGS_CALVES,
            ],
            // Adducteurs
            [
                'name' => 'Machine de fermeture des cuisses',
                'muscle_id' => Muscle::where('name', 'legs')->first()->id,
                'slug' => 'machine-de-fermeture-des-cuisses',
                'img' => 'machine-de-fermeture-des-cuisses.jpg',
                'tutorial' => 'machine-de-fermeture-des-cuisses-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'isolated',
                'difficulty' => 'intermediate',
                'polyarticular' => false,
                'muscle_part' => Exercise::LEGS_ADDUCTORS,
            ],
            [
                'name' => 'Écarté latéral aux câbles',
                'muscle_id' => Muscle::where('name', 'legs')->first()->id,
                'slug' => 'ecarte-lateral-aux-cables',
                'img' => 'ecarte-lateral-aux-cables.jpg',
                'tutorial' => 'ecarte-lateral-aux-cables-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'isolated',
                'difficulty' => 'intermediate',
                'polyarticular' => false,
                'muscle_part' => Exercise::LEGS_ADDUCTORS,
            ],
            // Fesses
            [
                'name' => 'Soulevé de terre jambes tendues',
                'muscle_id' => Muscle::where('name', 'legs')->first()->id,
                'slug' => 'souleve-de-terre-jambes-tendues',
                'img' => 'souleve-de-terre-jambes-tendues.jpg',
                'tutorial' => 'souleve-de-terre-jambes-tendues-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'advanced',
                'polyarticular' => true,
                'muscle_part' => Exercise::LEGS_GLUTES,
            ],
            [
                'name' => 'Fentes bulgares',
                'muscle_id' => Muscle::where('name', 'legs')->first()->id,
                'slug' => 'fentes-bulgares',
                'img' => 'fentes-bulgares.jpg',
                'tutorial' => 'fentes-bulgares-tutorial',
                'priority' => 90,
                'machine' => true,
                'type' => 'polyarticular',
                'difficulty' => 'intermediate',
                'polyarticular' => true,
                'muscle_part' => Exercise::LEGS_GLUTES,
            ],
        ];

        foreach ($exercises as $exercise) Exercise::create($exercise);
    }
}
